branches:
  only:
    - master

language: android
sudo: false
jdk:
  - oraclejdk8

android:
  components:
    - tools # to get the new `repository-11.xml`
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - doc-25
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'

before_install:
    - pip install --user codecov

script:
  - ./gradlew clean testDebugUnitTest jacocoTestReport --info

after_success:
  - codecov
  - ./scripts/publish_snapshot.sh

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository
